### PR TITLE
Fix/bugfixing

### LINKED ISSUE #118: [BUG] Descenders get cut off on template C's radio button labels
**Describe the bug**
See title.

### PR DESCRIPTION
**Pull request by aulonm**
Fixes #118 and #117

### CODE REVIEW

File: src/util/graph-templates/templateB.js [hunk 1]
```diff
@@ -104,9 +104,14 @@ function Template(svg) {
     // the selected geography will be affected by hover.
     voronoiCells.on('mouseover', (d, i, j) => {
       const geography = j[i].__data__.data.geography;
-      const date = j[i]['__data__']['data']['date'];
+      const date = j[i]['__data__'].data.date;
```
Comment (kiledal) [inline src/util/graph-templates/templateB.js]: `const date = j[i].__data__.data.date;` for consistency (?)
